name: build-apk
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Gradle 8.9
        run: |
          curl -L -o gradle.zip https://services.gradle.org/distributions/gradle-8.9-bin.zip
          unzip -q gradle.zip
          echo "$GITHUB_WORKSPACE/gradle-8.9/bin" >> $GITHUB_PATH

      - name: Build debug APK
        run: gradle :app:assembleDebug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: droid4linux-apk
          path: app/build/outputs/apk/debug/*.apk

